---
- name: Install iptables-persistent
  apt: name=iptables-persistent state=present

- name: Flush all rules
  iptables: flush=yes

- name: Allow related inbound
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT

- name: Allow SSH
  iptables: chain=INPUT protocol=tcp destination_port=22 jump=ACCEPT

- name: Allow HTTPS
  iptables: chain=INPUT protocol=tcp destination_port=443 jump=ACCEPT

- name: Block all incoming
  iptables: chain=INPUT jump=DROP

- name: Save iptables rules
  command: netfilter-persistent save

#- name: install iptables configuration
#  template: dest=/etc/iptables.rules src=iptables.j2 owner=root group=root mode=0600
#  notify:
#    - restart iptables
#
#- name: enable iptables service
#  service: name=ufw enabled=yes state=started
#
#- meta: flush_handlers
