---
issuer:
    address: http://10.211.55.2:5000

idstore:
    address: 10.211.55.8
    port: 389
    serviceaccountdn: 'cn=admin,dc=hd,dc=local'
    serviceaccountpassword: 'Password1'
    basesearchdn: 'dc=hd,dc=local'

claimattributes:
    sn: family_name
    givenName: given_name
    mail: email
    employeeNumber: employee_number

sessionstore:
    address: localhost
    port: 6379

session:
    jwtexpiryseconds: 28800

