---
issuer:
    address: http://10.211.55.2:5000

idservice:
    address: http://10.211.55.8:5001/getuserdetails

claimattributes:
    sn: family_name
    givenName: given_name
    mail: email
    employeeNumber: employee_number

sessionstore:
    address: localhost
    port: 6379

session:
    jwtexpiryseconds: 28800

