---

# Required infrastructure
# -----------------------

- hosts: all
  user: user1
  roles:
   - base
   - app
   - iptables
   - ssh
  vars:
    - type: idp
    - enable_sshd_timeout: false
    - iptables_inbound_ports:
      - { protocol: 'tcp', port: 443 }


